# Generated by Django 5.2.7 on 2025-10-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TheoreticalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "theoretical_models",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Nucleus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Z", models.IntegerField(db_index=True, help_text="Proton number")),
                ("N", models.IntegerField(db_index=True, help_text="Neutron number")),
                (
                    "element_symbol",
                    models.CharField(blank=True, db_index=True, max_length=3),
                ),
                ("element_name", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "nuclei",
                "ordering": ["Z", "N"],
                "indexes": [
                    models.Index(fields=["Z", "N"], name="nuclei_Z_6b2dfb_idx")
                ],
                "unique_together": {("Z", "N")},
            },
        ),
        migrations.CreateModel(
            name="MassRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BE",
                    models.FloatField(
                        blank=True, help_text="Binding Energy (MeV)", null=True
                    ),
                ),
                (
                    "MassExcess",
                    models.FloatField(
                        blank=True, help_text="Mass Excess (MeV)", null=True
                    ),
                ),
                (
                    "OneNSE",
                    models.FloatField(
                        blank=True,
                        help_text="One Neutron Separation Energy (MeV)",
                        null=True,
                    ),
                ),
                (
                    "OnePSE",
                    models.FloatField(
                        blank=True,
                        help_text="One Proton Separation Energy (MeV)",
                        null=True,
                    ),
                ),
                (
                    "TwoNSE",
                    models.FloatField(
                        blank=True,
                        help_text="Two Neutron Separation Energy (MeV)",
                        null=True,
                    ),
                ),
                (
                    "TwoPSE",
                    models.FloatField(
                        blank=True,
                        help_text="Two Proton Separation Energy (MeV)",
                        null=True,
                    ),
                ),
                (
                    "AlphaSE",
                    models.FloatField(
                        blank=True, help_text="Alpha Separation Energy (MeV)", null=True
                    ),
                ),
                (
                    "BetaMinusDecay",
                    models.FloatField(
                        blank=True,
                        help_text="Beta Minus Decay Q-Value (MeV)",
                        null=True,
                    ),
                ),
                (
                    "BetaPlusDecay",
                    models.FloatField(
                        blank=True, help_text="Beta Plus Decay Q-Value (MeV)", null=True
                    ),
                ),
                (
                    "ElectronCaptureQValue",
                    models.FloatField(
                        blank=True,
                        help_text="Electron Capture Q-Value (MeV)",
                        null=True,
                    ),
                ),
                (
                    "AlphaDecayQValue",
                    models.FloatField(
                        blank=True, help_text="Alpha Decay Q-Value (MeV)", null=True
                    ),
                ),
                (
                    "TwoNSGap",
                    models.FloatField(
                        blank=True, help_text="Two Neutron Shell Gap (MeV)", null=True
                    ),
                ),
                (
                    "TwoPSGap",
                    models.FloatField(
                        blank=True, help_text="Two Proton Shell Gap (MeV)", null=True
                    ),
                ),
                (
                    "u_BE",
                    models.FloatField(
                        blank=True, help_text="BE Uncertainty", null=True
                    ),
                ),
                (
                    "e_BE",
                    models.IntegerField(
                        blank=True, help_text="BE Estimated flag", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nucleus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mass_records",
                        to="bmexapp.nucleus",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mass_records",
                        to="bmexapp.theoreticalmodel",
                    ),
                ),
            ],
            options={
                "db_table": "mass_records",
                "indexes": [
                    models.Index(
                        fields=["nucleus", "model"],
                        name="mass_record_nucleus_f4142e_idx",
                    )
                ],
                "unique_together": {("nucleus", "model")},
            },
        ),
    ]
